# Generated by Django 5.2.7 on 2025-11-05 04:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='目的地名称')),
                ('slug', models.SlugField(help_text="用于URL的唯一标识，例如 'kuala-lumpur'", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '目的地',
                'verbose_name_plural': '目的地',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('hotel', '酒店'), ('ticket', '景点门票'), ('route', '路线规划'), ('transport', '交通工具')], default='hotel', max_length=10, verbose_name='素材类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题/名称')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='描述/行程')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='route_pdfs/', verbose_name='PDF文件 (仅路线规划)')),
                ('header_image', models.ImageField(blank=True, upload_to='material_headers/', verbose_name='头图/主图')),
                ('video', models.FileField(blank=True, null=True, upload_to='hotel_videos/', verbose_name='酒店视频 (仅酒店类型)')),
                ('compression_data', models.JSONField(blank=True, null=True, verbose_name='压缩信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.destination', verbose_name='所属目的地')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='material_gallery/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.material', verbose_name='所属素材')),
            ],
            options={
                'verbose_name': '素材图片',
                'verbose_name_plural': '素材图片库',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('faq', '常见问题'), ('ticket', '订票问题'), ('car', '汽车问题'), ('incident', '意外情况')], max_length=20, verbose_name='问题分类')),
                ('question_text', models.TextField(verbose_name='问题详细描述/标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False, verbose_name='是否已回答')),
                ('answer_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='管理员回答内容')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('is_public_faq', models.BooleanField(default=False, verbose_name='公开到知识库')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='提问/创建者')),
            ],
            options={
                'verbose_name': '支持工单/问答',
                'verbose_name_plural': '支持工单/问答库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
