# Generated by Django 5.2.7 on 2025-10-28 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='目的地名称')),
                ('slug', models.SlugField(help_text="用于URL的唯一标识，例如 'kuala-lumpur'", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '目的地',
                'verbose_name_plural': '目的地',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('hotel', '酒店'), ('ticket', '门票'), ('route', '路线规划')], default='hotel', max_length=10, verbose_name='素材类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题/名称')),
                ('description', models.TextField(blank=True, verbose_name='描述/行程')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='route_pdfs/', verbose_name='PDF文件 (仅路线规划)')),
                ('header_image', models.ImageField(blank=True, upload_to='material_headers/', verbose_name='头图/主图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.destination', verbose_name='所属目的地')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='material_gallery/', verbose_name='图片')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.material', verbose_name='所属素材')),
            ],
            options={
                'verbose_name': '素材图片',
                'verbose_name_plural': '素材图片库',
            },
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
