# Generated by Django 5.2.7 on 2025-11-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video',
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(help_text="用于URL的唯一标识,例如 'kuala-lumpur'", max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='material_videos/', verbose_name='视频文件')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='视频标题')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='视频描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='material_video_thumbnails/', verbose_name='视频缩略图')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.material', verbose_name='所属素材')),
            ],
            options={
                'verbose_name': '素材视频',
                'verbose_name_plural': '素材视频库',
                'ordering': ['order', 'id'],
            },
        ),
    ]
