# Generated by Django 5.2.7 on 2025-10-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_destination_material_materialimage_delete_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourLine',
        ),
    ]
