# Generated by Django 5.2.7 on 2025-11-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_material_video_alter_destination_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='header_image',
        ),
    ]
