# Generated by Django 5.2.7 on 2025-10-28 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_tourline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('faq', '常见问题'), ('ticket', '订票问题'), ('car', '汽车问题'), ('incident', '意外情况')], max_length=20, verbose_name='问题分类')),
                ('question_text', models.TextField(verbose_name='问题详细描述/标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False, verbose_name='是否已回答')),
                ('answer_content', models.TextField(blank=True, null=True, verbose_name='管理员回答内容')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('is_public_faq', models.BooleanField(default=False, verbose_name='公开到知识库')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='提问/创建者')),
            ],
            options={
                'verbose_name': '支持工单/问答',
                'verbose_name_plural': '支持工单/问答库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
