# Generated by Django 5.2.7 on 2025-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_material_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('hotel', '酒店'), ('ticket', '景点门票'), ('route', '路线规划'), ('transport', '交通工具'), ('restaurant', '餐厅')], default='hotel', max_length=10, verbose_name='素材类型'),
        ),
    ]
