"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# ===== 新增：导入环境变量管理 =====
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ===== 修改：使用环境变量 =====
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# ===== 修改：使用环境变量 =====
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ===== 修改：使用环境变量，支持多个域名 =====
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    "unfold",  
    "unfold.contrib.filters",  # 可选：高级过滤器
    "unfold.contrib.forms",  # 可选：表单增强
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # 'api',
    #apps
    'apps.users',
    'apps.materials',
    'apps.support',
    'django_ckeditor_5',

]


# CKEditor 5 专用配置 
customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                    }

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                      'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',
                    ],
            'shouldNotGroupWhenFull': 'true'
        },
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}



# 文件压缩配置
FILE_COMPRESSION_CONFIG = {
    'IMAGE': {
        'MAX_WIDTH': 1920,
        'MAX_HEIGHT': 1080, 
        'QUALITY': 85,
        'MIN_SIZE_TO_COMPRESS_MB': 0.5,  # 大于此大小的图片才压缩
    },
    'VIDEO': {
        'MAX_WIDTH': 1280,
        'MAX_HEIGHT': 720,
        'CRF': 23,
        'MIN_SIZE_TO_COMPRESS_MB': 2,  # 大于此大小的视频才压缩
    }
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ================== CORS 配置 ==================
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

# CSRF trusted
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# ================== Session 配置 ==================
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1天
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# 根据环境设置安全 Cookie
if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'  # 跨域时可改为 'None'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ===== 修改：数据库配置使用环境变量 =====
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='TH_Project'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default='112233'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# ===== Redis 缓存使用环境变量 =====
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config('REDIS_URL', default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": SESSION_COOKIE_AGE,
    }
}

# REST Framework + JWT 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ===== 修改：静态文件配置 =====
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static', # 这告诉 Django 去项目根目录下的 'static' 文件夹查找
    # 注意：如果你的 'static' 文件夹不在 BASE_DIR 下，请根据实际情况修改路径
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kuala_Lumpur'
USE_TZ = True
USE_I18N = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== 媒体文件配置 =====
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ===== PDF 字体配置 =====
PDF_FONT_DIR = os.path.join(BASE_DIR, 'static/fonts')
PDF_FONT_PATH = os.path.join(PDF_FONT_DIR, 'Alibaba-PuHuiTi-Regular.ttf')


# ==================== Lark 飞书配置 ====================
# ===== 修改：使用环境变量 =====
LARK_WEBHOOK_URL = config('LARK_WEBHOOK_URL', default="https://open.larksuite.com/open-apis/bot/v2/hook/caf8cb57-9af4-40ee-a472-a2b414af642c")
LARK_WEBHOOK_SECRET = config('LARK_WEBHOOK_SECRET', default=True)
LARK_ENABLE_NOTIFICATIONS = config('LARK_ENABLE_NOTIFICATIONS', default=True, cast=bool)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Lark OAuth 登录配置
LARK_APP_ID = config('LARK_APP_ID', default='')
LARK_APP_SECRET = config('LARK_APP_SECRET', default='')
LARK_REDIRECT_URI = config('LARK_REDIRECT_URI', default='http://localhost:5173/auth/lark/callback')

# Lark API 端点配置
LARK_CONFIG = {
    'OPEN_API_HOST': 'https://open.larksuite.com',
    'AUTH_URL': 'https://open.larksuite.com/open-apis/authen/v1/authorize',
    'TOKEN_URL': 'https://open.larksuite.com/open-apis/authen/v1/oidc/access_token',
    'USER_INFO_URL': 'https://open.larksuite.com/open-apis/authen/v1/user_info',
}


# ===== 修改：增强的日志配置 =====
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_error.log'),
            'formatter': 'verbose',
        },
        'file_info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_info.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        'api.lark_notification': {
            'handlers': ['console', 'file_info'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



# ==================== Unfold 配置 ====================
# 在 settings.py 文件末尾添加

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    # 网站基本信息 (保持不变)
    "SITE_TITLE": "素材管理系统",
    "SITE_HEADER": "素材库后台",
    "SITE_URL": "http://trippalholiday.my",
    
    # 网站图标 (保持不变)
    "SITE_ICON": {
        "light": lambda request: static("images/logo.svg"),
        "dark": lambda request: static("images/logo.svg"),
    },
    
    # 侧边栏配置
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("仪表盘"),
                "separator": True,
                "items": [
                    {
                        "title": _("首页"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("素材管理"),
                "separator": True,
             
                "items": [
                    {
                        "title": _("素材库"),
                        # 已经是 materials_material_changelist (正确)
                        "icon": "layers",
                        "link": reverse_lazy("admin:materials_material_changelist"), 
                    },
                    {
                        "title": _("目的地"),
                        "icon": "map",
                        # ❌ 修复：Destination 属于 materials app
                        "link": reverse_lazy("admin:materials_destination_changelist"), 
                    },
                    {
                        "title": _("总图片库"),
                        "icon": "image",
                        # ❌ 修复：MaterialImage 属于 materials app
                        "link": reverse_lazy("admin:materials_materialimage_changelist"),
                    },
                    {
                        "title": _("总视频库"),
                        "icon": "video_library",
                        # ❌ 修复：MaterialVideo 属于 materials app
                        "link": reverse_lazy("admin:materials_materialvideo_changelist"),
                    },
                ],
            },
            {
                "title": _("问答管理"),
                "separator": True,
                "items": [
                    {
                        "title": _("问答库"),
                        "icon": "book",
                        # ❌ 修复：SupportTicket 属于 support app
                        "link": reverse_lazy("admin:support_supportticket_changelist"), 

                    },
                ],
            },
            {
                "title": _("系统管理"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("用户"),
                        "icon": "group",
                        # auth_user 是 Django 内置的，保持不变 (正确)
                        "link": reverse_lazy("admin:auth_user_changelist"), 
                    },
                    {
                        "title": _("用户资料"),
                        "icon": "circle",
                        # ❌ 修复：UserProfile 属于 users app
                        "link": reverse_lazy("admin:users_userprofile_changelist"),
                    },
                    {
                        "title": _("权限组"),
                        "icon": "lock",
                        # auth_group 是 Django 内置的，保持不变 (正确)
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    
    # 主题颜色 (保持不变)
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
    
    # 标签页配置
    "TABS": [
        {
            "models": [
                # ❌ 修复：模型引用改为新的 app.model 格式
                "materials.material",
            ],
            "items": [
                {
                    "title": _("基本信息"),
                    "link": reverse_lazy("admin:materials_material_changelist"),
                },
                {
                    "title": _("图片管理"),
                    "link": reverse_lazy("admin:materials_materialimage_changelist"),
                },
                {
                    "title": _("视频管理"),
                    "link": reverse_lazy("admin:materials_materialvideo_changelist"),
                },
            ],
        },
    ],
}