# Generated by Django 5.2.7 on 2025-11-21 09:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='目的地名称')),
                ('slug', models.SlugField(help_text="用于URL的唯一标识,例如 'kuala-lumpur'", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '目的地',
                'verbose_name_plural': '目的地',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('hotel', '酒店'), ('ticket', '景点门票'), ('route', '路线规划'), ('transport', '交通工具'), ('restaurant', '餐厅')], default='hotel', max_length=10, verbose_name='素材类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题/名称')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='描述/行程')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='route_pdfs/', verbose_name='PDF文件 (仅路线规划)')),
                ('compression_data', models.JSONField(blank=True, null=True, verbose_name='压缩信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.destination', verbose_name='所属目的地')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='material_gallery/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material', verbose_name='所属素材')),
            ],
            options={
                'verbose_name': '素材图片',
                'verbose_name_plural': '素材图片库',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='material_videos/', verbose_name='视频文件')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='视频标题')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='视频描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='material_video_thumbnails/', verbose_name='视频缩略图')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='materials.material', verbose_name='所属素材')),
            ],
            options={
                'verbose_name': '素材视频',
                'verbose_name_plural': '素材视频库',
                'ordering': ['order', 'id'],
            },
        ),
    ]
